using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Windows.Forms;

namespace RedlineTest
{

    /// <summary>
    /// 
    /// </summary>
    public partial class TestForm : Form
    {

        /// <summary>
        /// 
        /// </summary>
        public TestForm()
        {
            InitializeComponent();

            this.RadioCreate.Checked = true;
        }

        #region Store page

        private void ButtonChoose1_Click(object sender, EventArgs e)
        {
            OpenFileDialog dlg = new OpenFileDialog();
            dlg.AddExtension = true;
            dlg.CheckFileExists = true;
            dlg.Multiselect = true;
            dlg.Title = "Select files to store";

            if (dlg.ShowDialog() == DialogResult.OK)
            {
                listBox1.Items.Clear();
                listBox1.Items.AddRange(dlg.FileNames);
            }
        }

        private void ButtonBrowse1_Click(object sender, EventArgs e)
        {
            FileDialog dlg;

            if (this.RadioCreate.Checked)
            {
                dlg = new SaveFileDialog();
                ((SaveFileDialog)dlg).OverwritePrompt = true;
            }
            else
            {
                dlg = new OpenFileDialog();
                dlg.CheckFileExists = true;
            }

            dlg.AddExtension = true;
            dlg.Filter = "Zip file|*.zip";
            dlg.Title = "Select filename for storage file";

            if (dlg.ShowDialog() == DialogResult.OK)
            {
                TextStorage1.Text = dlg.FileName;
            }
        }

        private void RadioCreate_CheckedChanged(object sender, EventArgs e)
        {
            this.TextStorage1.Text = "";
        }
        private void RadioAppend_CheckedChanged(object sender, EventArgs e)
        {
            this.TextStorage1.Text = "";
        }

        private void ButtonProceed1_Click(object sender, EventArgs e)
        {

            if (this.listBox1.Items.Count <= 0)
            {
                MessageBox.Show("Source files not chosen.", "Redline Test", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                return;
            }
            if (string.IsNullOrEmpty(TextStorage1.Text))
            {
                MessageBox.Show("Target filename not defined.", "Redline Test", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                return;
            }

            try
            {
                Redline zip;

                if (this.RadioCreate.Checked)

                    zip = Redline.Create(TextStorage1.Text, "Generated by Redline");
                else

                    zip = Redline.Open(TextStorage1.Text, FileAccess.Write);

                zip.EncodeUTF8 = this.CheckUTF8.Checked;

                foreach (string path in listBox1.Items)
                {
                    zip.AddFile(this.checkCompress.Checked ? Redline.Compression.Deflate : Redline.Compression.Store, 
                        path, Path.GetFileName(path), "");
                }

                if (this.RadioCreate.Checked)
                {
                    MemoryStream readme = new MemoryStream(
                        System.Text.Encoding.UTF8.GetBytes(string.Format("{0}\r\nThis file has been {1} using the Redline class.",
                        DateTime.Now, this.RadioCreate.Checked ? "created" : "appended")));

                    zip.AddStream(Redline.Compression.Store, "readme.txt", readme, DateTime.Now, "Please read");
                    readme.Close();
                }

                zip.Close();

                MessageBox.Show("Target file processed with success.", "Redline Test", MessageBoxButtons.OK, MessageBoxIcon.Information);

                this.listBox1.Items.Clear();
                this.TextStorage1.Text = "";
            }
            catch (InvalidDataException)
            {
                MessageBox.Show("Error: Invalid or not supported Zip file.", "Redline Test", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            catch
            {
                MessageBox.Show("Error while processing target file.", "Redline Test", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
        #endregion

        #region Extract page
        private void ButtonBrowse2_Click(object sender, EventArgs e)
        {
            OpenFileDialog dlg = new OpenFileDialog();
            dlg.AddExtension = true;
            dlg.CheckFileExists = true;
            dlg.Multiselect = false;
            dlg.Title = "Select storage file";

            if (dlg.ShowDialog() == DialogResult.OK)
            {
                TextStorage2.Text = dlg.FileName;
                if (string.IsNullOrEmpty(TextTargetFolder.Text))
                    TextTargetFolder.Text = Path.GetDirectoryName(TextStorage2.Text);
                listBox2.Items.Clear();
            }
        }
        private void ButtonBrowse2a_Click(object sender, EventArgs e)
        {
            FolderBrowserDialog dlg = new FolderBrowserDialog();
            dlg.Description = "Select target folder for extracted files:";
            dlg.ShowNewFolderButton = true;

            if (dlg.ShowDialog() == DialogResult.OK)
            {
                TextTargetFolder.Text = dlg.SelectedPath;
            }
        }
        private void ButtonProceed2_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(TextStorage2.Text))
            {
                MessageBox.Show("Storage filename not defined.", "ZipStorer Demo", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                return;
            }
            if (string.IsNullOrEmpty(TextTargetFolder.Text))
            {
                MessageBox.Show("Target folder not defined.", "ZipStorer Demo", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                return;
            }

            try
            {
                Redline zip = Redline.Open(TextStorage2.Text, FileAccess.Read);

                List<Redline.ZipFileEntry> dir = zip.ReadCentralDir();
                this.listBox2.Items.Clear();

                string path;
                bool result;
                foreach (Redline.ZipFileEntry entry in dir)
                {
                    path = Path.Combine(TextTargetFolder.Text, Path.GetFileName(entry.FilenameInZip));
                    result = zip.ExtractFile(entry, path);
                    this.listBox2.Items.Add(path + (result ? "" : " (error)"));
                }
                zip.Close();

                MessageBox.Show("Source file processed with success.", "Redline Test", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (InvalidDataException)
            {
                MessageBox.Show("Error: Invalid or not supported Zip file.", "Redline Test", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            catch
            {
                MessageBox.Show("Error while processing source file.", "Redline Test", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
        #endregion

        #region Remove page
        private void ButtonBrowse4_Click(object sender, EventArgs e)
        {
            OpenFileDialog dlg = new OpenFileDialog();
            dlg.AddExtension = true;
            dlg.CheckFileExists = true;
            dlg.Multiselect = false;
            dlg.Title = "Select storage file";

            if (dlg.ShowDialog() == DialogResult.OK)
            {
                TextStorage4.Text = dlg.FileName;

                Redline zip = Redline.Open(TextStorage4.Text, FileAccess.Read);

                List<Redline.ZipFileEntry> dir = zip.ReadCentralDir();
                listBox4.Tag = zip;

                listBox4.DataSource = dir;
            }
        }
        private void ButtonProceed4_Click(object sender, EventArgs e)
        {
            List<Redline.ZipFileEntry> removeList = new List<Redline.ZipFileEntry>();

            foreach (object sel in listBox4.SelectedItems)
            {
                removeList.Add((Redline.ZipFileEntry)sel);
            }

            Redline zip = listBox4.Tag as Redline;
            try
            {
                if (zip == null || !Redline.RemoveEntries(ref zip, removeList))
                {
                    throw new Exception();
                }
                else
                {
                    MessageBox.Show("Zip file entries removed with success", "Redline Test", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    listBox4.Tag = zip;
                    listBox4.DataSource = zip.ReadCentralDir();
                }
            }
            catch
            {
                MessageBox.Show("Error while trying to remove entries from Zip file", "Redline Test", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
        #endregion

        #region Credits page
        private void linkLabel1_LinkClicked(object sender, LinkLabelLinkClickedEventArgs e)
        {
            System.Diagnostics.Process.Start("http://zipstorer.codeplex.com");
        }
        private void pictureBox1_Click(object sender, EventArgs e)
        {
            System.Diagnostics.Process.Start("http://www.codeplex.com/site/users/view/jaime_olivares");
        }
        private void pictureBox2_Click(object sender, EventArgs e)
        {
            System.Diagnostics.Process.Start(
                "https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=jaime_olivares%40hotmail%2ecom&lc=PE&item_name=Jaime%20Olivares&item_number=CODEPLEX&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted");
        }
        #endregion

        private void TestForm_Load(object sender, EventArgs e)
        {

        }
    }
}
